version: "3.7"

services:
  # first container
  service:
    # look for dockerfile and build the container
    build:
      context: .
      target: deployment
    container_name: service
    restart: always
    # mount the volumes so we can change code and hot reload
    volumes:
      - ".:/service"
    ports:
      - 127.0.0.1:80:80

  redis:
    restart: always
    container_name: redis
    image: "redis:6.2.4-alpine"
    expose:
      - 6379
